config/routes.rb
Rails.application.routes.draw do
  root "rooms#index"
  post 'report_log', to: "logs#report" 
  resources  :rooms
  resources :sensors
  resources :logs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :sensor
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/sensor.rb
class Sensor < ApplicationRecord
  belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.all
  end
  def report
    if params[:token] == 'ere4ereEElp$QQwwwQQasl0029'
      log = Log.new
      log.temperture = params[:temp]
      log.humidity = params[:humidity]
      log.sensor_id = params[:sensor_id]
      log.save!
      respond_to do |format|
        format.json { head :no_content }
      end
    end
  end
  # GET /logs/1
  # GET /logs/1.json
  def show
  end

  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = Log.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def log_params
      params.fetch(:log, {})
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  def analize_report
    data = params[json]
  end
  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to root_path, notice: 'Reefer creado con exito' }
      else
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Reefer actualizado con exito' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    sens = Sensor.where(room_id:@room.id)
    sens.each do |sensor|
      sensor.destroy!
    end
    @room.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Reefer eliminado con exito' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.fetch(:room, {}).permit(:name)
    end
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]

  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to root_path, notice: 'Sensor Creado con exito!' }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    idd = @sensor.room_id
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to room_path(idd), notice: 'Sensor destruido con exito' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sensor_params
      params.fetch(:sensor, {}).permit(:room_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RemoteFarm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <%= stylesheet_pack_tag 'src/application',media: 'all'%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="pos-f-t">
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4">
      <h4 class="text-white">Tomas Remote Farm TRF</h4>
      <%=link_to "Home", root_path,style: ["color:white"]%>
    </div>
  </div>
  <nav class="navbar navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</div>
    <%= yield %>
  </body>
</html>

app/views/logs/_form.html.erb
<%= form_with(model: log, local: true) do |form| %>
  <% if log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
        <% log.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Logs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= link_to 'Show', log %></td>
        <td><%= link_to 'Edit', edit_log_path(log) %></td>
        <td><%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Log', new_log_path %>

app/views/logs/new.html.erb
<h1>New Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>

app/views/rooms/_form.html.erb
<div class="card" style="width: 20rem; margin-top:10px">
  <div class="card-header"><h4>Crear nuevo Reefer </h4></div>
<%= form_with(model: room, local: true) do |form| %>
  <%= form.label(:name, "Nombre") %>
  <%= form.text_field(:name) %>

  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<div class="row">
    <div class="col-1"></div>
    <div class="col-8">
    <p id="notice"><%= notice %></p>
    <div class="shadow p-3 mb-5 bg-white rounded">  <h1>Reefer disponibles dentro de las Instalaciones</h1></div>
        <table class="table table-striped">
        <tr>
        <th>Reefer #</th>
        <th>Nº de sensores</th>
        <th>Nombre</th>

        <th>Accion</th>
          <th>Accion #2</th>

        </tr>
        <tbody>
        <%cont = 1%>
        <% Room.all.each do |room|%>
        <tr>
        <td><%= cont%></td>
        <%cont+=1%>
        <td><%=Sensor.where(room_id:room.id).count%></td> 
        <td><%= room.name%></td>
        <td><%= link_to "Ver",room_path(room.id),class: ["btn btn-primary"]%></td>
          <td><%= link_to "Eliminar",room_path(room.id),class: ["btn btn-danger"],:data => {:confirm => 'Seguro que desea eliminar sensor?'},method: :delete%></td>

        </tr>
        <%end%>       
        </tbody>
        </table>
    </div>
    <div class="col-3">
                <%@sensor = Sensor.new%>
                <%= render :partial => "sensors/form", :locals => { :sensor => @sensor }  %>

      <%@room = Room.new%>
      <%= render :partial => "rooms/form", :locals => { :room => @room }  %>
    </div>
</div>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<div class="row">
    <div class="col-1"></div>
    <div class="col-8">
    <p id="notice"><%= notice %></p>
    <div class="shadow p-3 mb-5 bg-white rounded"><h1>Sensores Disponibles del Reefer <%= @room.id%></h1>
</div>
        <div class="row">
        <% sens = Sensor.where(room_id:@room.id)%>
        <%sens.each do |s|%>
            <div class="col-6" style="margin-top:10px">
                <%= render :partial => "sensors/thumbnail", :locals => { :sensor => s }  %>
            </div>
            <%end%>
        </div>
        <div class="row">
            <div class="col-6"></div>
            <div class="col-6"></div>
        </div>
    </div>
    <div class="col-3">
    </div>
</div>

app/views/sensors/_form.html.erb
<div class="card" style="width: 20rem; margin-top:10px">
<div class="card-header"><h4>Crear nuevo sensor </h4></div>
<%= form_with(model: sensor, local: false) do |form| %>
<ul>
  <li style="list-style: none">
    <% room = Room.all %>
    <%= form.label(:room_id, "Reefer") %>

    <%= form.collection_select :room_id, room.order(:name),:id,:name, include_blank: true %>
  </li>
</ul>
  <% if sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
        <% sensor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
  </div>

app/views/sensors/_new.html.erb
<h1>New Sensor</h1>

<%= render 'form', sensor: @sensor %>

app/views/sensors/_thumbnail.html.erb
<div class="card" style="background:#fafafa">
  <div class="card-body">
<h4>Sensor Id: <%= sensor.id%></h4>
    <p class="card-text">Sensor humedad y temperatura con 8 protocolos</p>
  </div>
  <%e =  Log.where(sensor_id:sensor.id).count%>
  <%if e != 0%>
    <%r =  Log.where(sensor_id:sensor.id).last%>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Temperatura: <%=r.temperture%>º</li>
    <li class="list-group-item">Humedad tierra: 30%</li>
    <li class="list-group-item">Humedad aire: 20%</li>
  </ul>
  <% else %>
    <ul class="list-group list-group-flush">
    <li class="list-group-item">Temperatura: 20º</li>
    <li class="list-group-item">Humedad tierra: 30%</li>
    <li class="list-group-item">Humedad aire: 20%</li>
  </ul>
  <% end %>
  <div class="card-body">
    <a href="#" class="card-link">Registros <%= Log.where(sensor_id:sensor.id).count%></a>
    <%= link_to "Eliminar Sensor", sensor_path(sensor.id),class: ["btn","btn-danger"],method: :delete,:data => {:confirm => 'Seguro que desea eliminar sensor?'} %>
  </div>
</div>

app/views/sensors/edit.html.erb
<h1>Editing Sensor</h1>

<%= render 'form', sensor: @sensor %>

<%= link_to 'Show', @sensor %> |
<%= link_to 'Back', sensors_path %>

app/views/sensors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sensors</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sensors.each do |sensor| %>
      <tr>
        <td><%= link_to 'Show', sensor %></td>
        <td><%= link_to 'Edit', edit_sensor_path(sensor) %></td>
        <td><%= link_to 'Destroy', sensor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sensor', new_sensor_path %>

app/views/sensors/new.html.erb
<h1>New Sensor</h1>

<%= render 'form', sensor: @sensor %>

<%= link_to 'Back', sensors_path %>

app/views/sensors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sensor_path(@sensor) %> |
<%= link_to 'Back', sensors_path %>